import uuid
from datetime import datetime
from sqlalchemy import Column, DateTime, String, JSON
from sqlalchemy.dialects.postgresql import UUID

from app.database.database import Base


class ResearchInsightRecord(Base):
    __tablename__ = "research_insights"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(String, nullable=True, index=True)
    product_name = Column(String, nullable=False, default="Target Product Concept")
    industry = Column(String, nullable=False, default="Software & Technology")
    
    # Stored analytical JSON blobs generated by the Insight Extraction Agent
    themes = Column(JSON, nullable=False, default=list)
    sentiment_breakdown = Column(JSON, nullable=False, default=dict)
    agreement_patterns = Column(JSON, nullable=False, default=list)
    behavioral_trends = Column(JSON, nullable=False, default=list)
    validation_scores = Column(JSON, nullable=False, default=dict) # "Would use this product?" scores + reasoning per segment
    key_quotes = Column(JSON, nullable=False, default=list)
    actionable_recommendations = Column(JSON, nullable=False, default=list)
    
    created_at = Column(DateTime, default=datetime.utcnow)
